# 全局选项（作用于整个 ffmpeg 进程）
global_options:
  - "-y"                     # 覆盖输出文件
  # - "-loglevel"
  # - "error"                  # 只显示错误（使用error则进度展示功能失效）

# 输入选项（作用于 -i 之前的参数）
input_options:
  - "-ss"
  - "00:00:10"               # 从第10秒开始（示例）
  # - "-t"
  # - "30"                   # 截取30秒

# 输出选项（作用于输出文件前的编码参数）
output_options:
  - "-c:v"
  - "hevc_nvenc"
  - "-rc"
  - "vbr"
  - "-cq"
  - "23"
  - "-c:a"
  - "aac"

# 输出格式后缀
output_format: "mp4"
output_dir: "./dist/output"
# 自定义后缀 (用于文件名)
output_suffix: "_test"
# 文件名模板 (可选，如果不设置则使用默认逻辑)
# 支持变量: $name (原名), $custom (自定义字段), $ext (格式)
output_template: "$name$custom.$ext"